export default {
  uid: undefined,
  version: undefined,
  extJson: undefined,
  createDatetime: undefined,
  createUserId: undefined,
  createUser: undefined,
  lastModifyDatetime: undefined,
  lastModifyUserId: undefined,
  lastModifyUser: undefined,
  invalid: undefined,
  invalidDatetime: undefined,
  invalidUserId: undefined,
  invalidUser: undefined,
}
