export default {
  id: undefined,
  version: undefined,
  extJson: undefined,
  createDatetime: undefined,
  createUserId: undefined,
  createUser: undefined,
  lastModifyDatetime: undefined,
  lastModifyUserId: undefined,
  lastModifyUser: undefined,
  invalid: '0',
  invalidDatetime: undefined,
  invalidUserId: undefined,
  invalidUser: undefined,
}
